#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# set wmname
wmname LG3D

# set wallpaper
nitrogen --restore &

# start picom compositor
picom &

# start status bar
~/.config/polybar/launch.sh --colorblocks

# start authentication agent
lxpolkit &

# xsetroot
xsetroot -cursor_name left_ptr &

# set locker
xautolock -locker "betterlockscreen -l" &

# other stuffs
fcitx5 -d
blueberry-tray &
kdeconnect-indicator &
